// <auto-generated />
using System;
using FoodProduction.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodProduction.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FoodProduction.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPerKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("FoodProduction.Models.LabelTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LabelTemplates");
                });

            modelBuilder.Entity("FoodProduction.Models.Pack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Printed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("FoodProduction.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefaultGainPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultLabelTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultLabelTemplateId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FoodProduction.Models.ProductFormulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Ratio")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFormulations");
                });

            modelBuilder.Entity("FoodProduction.Models.ProductionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GainPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductionBatches");
                });

            modelBuilder.Entity("FoodProduction.Models.Pack", b =>
                {
                    b.HasOne("FoodProduction.Models.ProductionBatch", "Batch")
                        .WithMany("Packs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("FoodProduction.Models.Product", b =>
                {
                    b.HasOne("FoodProduction.Models.LabelTemplate", "DefaultLabelTemplate")
                        .WithMany("Products")
                        .HasForeignKey("DefaultLabelTemplateId");

                    b.Navigation("DefaultLabelTemplate");
                });

            modelBuilder.Entity("FoodProduction.Models.ProductFormulation", b =>
                {
                    b.HasOne("FoodProduction.Models.Ingredient", "Ingredient")
                        .WithMany("ProductFormulations")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodProduction.Models.Product", "Product")
                        .WithMany("Formulations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodProduction.Models.ProductionBatch", b =>
                {
                    b.HasOne("FoodProduction.Models.Product", "Product")
                        .WithMany("ProductionBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodProduction.Models.Ingredient", b =>
                {
                    b.Navigation("ProductFormulations");
                });

            modelBuilder.Entity("FoodProduction.Models.LabelTemplate", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FoodProduction.Models.Product", b =>
                {
                    b.Navigation("Formulations");

                    b.Navigation("ProductionBatches");
                });

            modelBuilder.Entity("FoodProduction.Models.ProductionBatch", b =>
                {
                    b.Navigation("Packs");
                });
#pragma warning restore 612, 618
        }
    }
}
